apiVersion: v1
kind: Service
metadata:
  name: {{ include "ndc-testcontainer.fullname" . }} 
  labels:
    {{- include "ndc-testcontainer.labels" . | nindent 4 }} 
spec:
  type: {{ .Values.service.type }} 
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }} 
  selector:
    {{- include "ndc-testcontainer.selectorLabels" . | nindent 4 }}

